### PR TITLE
Add python 3.4 support

### PR DESCRIPTION
**Pull request by EvaSDK**
Branch for review, please do not click merge from the WebUI.

### CODE REVIEW

**Comment by EvaSDK** [comment]
Closing as there seems to be no interest in this and I have moved to other things.

**Comment by brmzkw** [comment]
I missed this pull request. I'll work to merge it to master asap.

**Comment by kdeldycke** [comment]
@moul can you check GitHub integration with Travis ? Looks like the project is still attached to its old URL (`https://travis-ci.org/online-labs/ocs-sdk/`), hence the failing tests.

**Comment by moul** [comment]
Yep sure

**Comment by moul** [comment]
The migration seems to be taken into account by travis, see: https://travis-ci.org/scaleway/python-scaleway/builds

This PR is older than the migration, can you try to git push a dummy commit then git push -f HEAD~1 to trigger a new build ?

**Comment by kdeldycke** [comment]
@moul ah yes. Everything's fine then. We'll just wait for @brmzkw to resume work on this PR for Travis to pick-up the pending work. No need to rush things out.

**Pull request closed without merging**
