### PR TITLE
feat(billing): added billing API

### PR DESCRIPTION
**Pull request by martintamare**
Just copy paste account api to billing api

### CODE REVIEW

**Comment by brmzkw** [comment]
You should not have copied the AccountAPI base class. The permission checks are not necessary here.

I made a commit with the feature here, it's much simpler: https://github.com/scaleway/python-scaleway/commit/f1cdf45ab9bdbb246139e19254b8802991c6d018

To use it:

```
import json

from scaleway.apis import BillingAPI

api = BillingAPI(auth_token='xx')
print (json.dumps(api.query().invoices().get())
```

Feel free to open an issue or create a PR if you think something is missing!

Thanks for your contribution :-)

**Comment by martintamare** [comment]
Awesome thanks !
I will look into it and add a method to get the url of the PDF for an invoice.

**Comment by brmzkw** [comment]
Here is a snippet to download an invoice programmatically.

We are making huge improvements in our billing stack. The API is not yet stable, and will change in the future. We should probably document it somewhere.

```python
import datetime

from scaleway.apis.api_billing import BillingAPI

ORGANIZATION_ID = 'xxx'
AUTH_TOKEN = 'xxx'
INVOICE_ID = 'xxx'

INVOICE_YEAR = 2017
INVOICE_MONTH = 1

api = BillingAPI(auth_token=AUTH_TOKEN)

invoice_date = datetime.datetime(
    year=INVOICE_YEAR, month=INVOICE_MONTH, day=1
).isoformat()


# Mandatory hack: x-auth-token must be given with **kwargs since it currently *must* contain dashes and not underscores, and be in the URL
kwargs = {
    'format': 'pdf',
    'x-auth-token': AUTH_TOKEN
}
ret = api.query().invoices(ORGANIZATION_ID)(invoice_date + '+00:00')(INVOICE_ID).get(**kwargs)

# ret contains the PDF, you can save it with open('invoice.pdf', 'w+').write(ret)
print ret
```

**Comment by kdeldycke** [comment]
Indeed. As @brmzkw said the whole billing domain is currently being revamped under the scenes.

That being said, if you want to help me on that, feel free to send your profile to us: https://careers.scaleway.com/job/billing-and-payments-software-engineer ! 😃

**Comment by kdeldycke** [comment]
BTW, if you'd like to complement our public API documentation, feel free to send a PR on https://github.com/scaleway/api.scaleway.com to add a detailed description of billing endpoints.

**Comment by martintamare** [comment]
Documentation is not my favorite part, but I keep that in mind ;)

**Comment by martintamare** [comment]
Hello there !

It seems the method to get PDF invoice is not working any more.
Could I get some input on this ?

Regards,

**Comment by martintamare** [comment]
Issue identified by checking real calls on console

`import datetime

from scaleway.apis.api_billing import BillingAPI

ORGANIZATION_ID = 'xxx'
AUTH_TOKEN = 'xxx'
INVOICE_ID = 'xxx'

INVOICE_YEAR = 2017
INVOICE_MONTH = 1

api = BillingAPI(auth_token=AUTH_TOKEN)

invoice_date = datetime.datetime(
    year=INVOICE_YEAR, month=INVOICE_MONTH, day=1
).isoformat()


# Mandatory hack: x-auth-token must be given with **kwargs since it currently *must* contain dashes and not underscores, and be in the URL
kwargs = {
    'format': 'pdf',
    'x-auth-token': AUTH_TOKEN
}
# The + '00:00' is no longer needed
ret = api.query().invoices(ORGANIZATION_ID)(invoice_date)(INVOICE_ID).get(**kwargs)

# ret contains the PDF, you can save it with open('invoice.pdf', 'w+').write(ret)
print ret
 `

**Pull request closed without merging**
